[package]
name = "touch"    # あなたのプロジェクト名に置き換えられます。
version = "0.1.0"
authors = ["Ryosuke <ryosuke_666@icloud.com>"]  # あなたの名前とメールアドレスで置き換えられます。
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"

